markdown: rdiscount
url: http://hellorld.github.io
highlighter: pygments
name: 楚风沉思录
description: 楚风沉思录 | stay hungry, stay foolish.
author: SlowCoder
email: chufeng1900@outlook.com
weibo: 1718106751
duoshuo: hellorld
hub: hellorld
safe: true
paginate: 30
permalink: /:year/:month/:day/:title
about: "大菜鸟"
