markdown: rdiscount
url: http://hellorld.github.io
highlighter: pygments
name: 笨笨的程序员
description: 笨笨的程序员 | stay hungry, stay foolish.
author: SlowCoder
email: qifengcheng@outlook.com
weibo: 1718106751
hub: hellorld
safe: true
paginate: 100
about: "大菜鸟"
